### ISSUE TITLE
Blocked status after relate to postgresql-k8s

### ISSUE THREAD

**Issue by jneo8** [canonical/candid#159]
Working on microk8s 1.24/stable

The charm is build from latest master branch
Still get blocked status `POSTGRESQL_DSN configuration value not set` after add-relation with command `juju add-relation candid-k8s:db postgresql-k8s:db`

```
bundle: kubernetes
applications:
  candid-k8s:
    charm: local:candid-k8s-0
    scale: 1
    options:
      admin-agent-public-key: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSURyVDZSWnpZdlpKL25Pb2ZOMVNIT3hPeWkyVmpSOHozWmR2bjVpNUszZjAgdWJ1bnR1QGppbW0K
      identity-providers: "- type: static                                 \n  name:
        static\n  domain: stimec\n  description: Default identity provider\n  users:\n
        \   admin:\n      name: User One\n      email: admin\n      password: password1\n
        \     groups:\n       - group1\n    user1:\n      name: User Two\n      email:
        user1\n      password: password1\n      groups:\n       - group2\n    my-user:\n
        \     name: User Three\n      email: my-user\n      password: password1\n
        \     groups:\n      - group2"
      location: https://candid.canonical.stimec.net
    constraints: arch=amd64
  postgresql-k8s:
    charm: postgresql-k8s
    channel: edge
    revision: 32
    resources:
      postgresql-image: 27
    scale: 3
    constraints: arch=amd64
    storage:
      pgdata: kubernetes,1,1024M
    trust: true
  tls-certificates-operator:
    charm: tls-certificates-operator
    channel: latest/edge
    revision: 15
    scale: 1
    options:
      ca-common-name: jneo8
      generate-self-signed-certificates: true
    constraints: arch=amd64
relations:
- - tls-certificates-operator:certificates
  - postgresql-k8s:certificates
- - candid-k8s:db
  - postgresql-k8s:db

```
